name: "Release Prep"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Template version, must match the version for the PDK release it is being bundled with."
        required: true

jobs:
  release_prep:
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_release_prep.yml@main"
    with:
      version: "${{ github.event.inputs.version }}"
    secrets: "inherit"
